optim: adam
init: null
log_interval: 1
max_epoch: 100
batch_type: unsorted
batch_size: 96 # batch_size 16 can be trained on 4 RTX 2080ti
iterator_type: chunk
chunk_length: 32000
num_workers: 4
unused_parameters: true
optim_conf:
    lr: 1.0e-03
    eps: 1.0e-08
    weight_decay: 0
patience: 4
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - si_snr
    - max
-   - valid
    - loss
    - min
keep_nbest_models: 1
scheduler: reducelronplateau
scheduler_conf:
    mode: min
    factor: 0.5
    patience: 1
model_conf:
    loss_type: si_snr
encoder: wav2vec
encoder_conf:
    checkpoint: /data3/xlsr_53_56k.pt 
    pre_rate: 16000
    kernel_size: 640
    stride: 320
# encoder: conv
# encoder_conf:
    # channel: 1024
    # kernel_size: 320
    # stride: 160
decoder: conv
decoder_conf:
    channel: 1024
    kernel_size: 320
    stride: 160
separator: tcn
separator_conf:
    num_spk: 2
    layer: 8
    stack: 4
    bottleneck_dim: 256
    hidden_dim: 512
    kernel: 3
    causal: False
    norm_type: "gLN"
    nonlinear: relu

